name: 'GCP Terragrunt Production'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: 'Deploy to Mumbai'
    runs-on: ubuntu-latest
    
    # CRITICAL: This allows the job to access the "production" environment secrets
    environment: production 
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          # These now correctly pull from your "production" environment
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_POOL }}/providers/${{ secrets.GCP_WORKLOAD_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          sudo wget -q -O /usr/local/bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.0/terragrunt_linux_amd64"
          sudo chmod +x /usr/local/bin/terragrunt
          terragrunt --version

      - name: Terragrunt Init & Apply
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            #terragrunt run-all plan --terragrunt-non-interactive
            terragrunt run-all destroy --terragrunt-non-interactive
          else
            terragrunt run-all apply --terragrunt-non-interactive
          fi